#!/bin/bash
#
# Stops the Docker registry server container.
#
set -o nounset

function fail {
  echo $1 >&2
  exit 1
}

trap 'fail "The execution was aborted because a command exited with an error status code."' ERR

DIR=`dirname "$(readlink -f "$0")"`
source "$DIR/common"

[ "$(id -u)" -eq "0" ] || fail "This script must be run as root"

docker stop "$REGISTRY_CONTAINER_NAME"

echo "Docker registry server stopped"
