#!/bin/sh
#
# Builds the work environment image.
#
fail () {
  echo $1 >&2
  exit 1
}

docker version > /dev/null 2> /dev/null || fail "Docker must be installed to use this script."

docker build --rm --tag="azure-docker-registry-workenv" workenv || fail "Error building work environment."
