#!/bin/sh
#
# Runs the work environment in a container.
#
fail () {
  echo $1 >&2
  exit 1
}

docker version > /dev/null 2> /dev/null || fail "Docker must be installed to use this script."

WORKENV="azure-docker-registry-work-environment"

docker inspect "$WORKENV" > /dev/null 2> /dev/null
if [ $? -eq 0 ]; then
  echo "Running container $WORKENV"
  docker start -ai "$WORKENV"
else
  echo "Creating container $WORKENV"
  docker run --name="$WORKENV" -v `pwd`/tools:/mnt/tools -v /tmp:/mnt/tmp -t -i azure-docker-registry-workenv /sbin/my_init -- bash -l
fi
